config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :groups

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	before_action :find_group, only: [:show, :edit, :update, :destroy]

	def index
		@groups = Group.all.order("created_at DESC")
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(groups_params)

		if @group.save
			redirect_to @group
		else
			render "New"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @group.update(groups_params)
			redirect_to @group
		else
			render "Edit"
		end
	end

	def destroy
		@group.destroy
		redirect_to root_path
	end

	private

	def groups_params
		params.require(:group).permit(:title, :description, :group_id, :url)
	end

	def find_group
		@group = Group.find(params[:id])
	end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb

<%= simple_form_for(@group, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.collection_select :group_id, Group.all, :id, :title, {promt: "Choose a group"} %>
	<%= f.input :title, label: "Group Title" %>
	<%= f.input :description, label: "Group Description Title" %>
	<%= f.input :url, label: "Link to Group" %>
	<button>
		<%= f.button :submit %>
	</button>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/groups/index.html.erb
<% @groups.each do |group| %>
	<h1>
  	<%= link_to group.title, group %>
	</h1>
<% end %>

<%= link_to "New Group", new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/groups/show.html.erb
<h1>
  <%= @group.title %>
</h1>
<p><%= @group.description %></p>

<%= link_to "Home", root_path, class: "btn btn-sm btndefaul" %>
<%= link_to "Join", class: "btn btn-sm btndefaul" %>
<%= link_to "Back", groups_path, class: "btn btn-sm btndefaul" %>
<%= link_to "Edit", edit_group_path(@group), class: "btn btn-sm btndefaul" %>
<%= link_to "Delete", group_path(@group), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-sm btndefaul" %>